// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZTOb4koSCTiqtl1PBHdUd8rl-5ckzFsA',
    appId: '1:249666842734:web:34f2be89db0bc8dc74b67f',
    messagingSenderId: '249666842734',
    projectId: 'basic-786d3',
    authDomain: 'basic-786d3.firebaseapp.com',
    storageBucket: 'basic-786d3.appspot.com',
    measurementId: 'G-L5030D6QHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgTRcTyYAY0JyD63D7-pmwz7_eGwLn5-4',
    appId: '1:249666842734:android:8d3a194c55773da674b67f',
    messagingSenderId: '249666842734',
    projectId: 'basic-786d3',
    storageBucket: 'basic-786d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfZEOkE2UHFoANKC__i4fXwdIxDaR-6EQ',
    appId: '1:249666842734:ios:6196781f30f9ce7374b67f',
    messagingSenderId: '249666842734',
    projectId: 'basic-786d3',
    storageBucket: 'basic-786d3.appspot.com',
    iosClientId: '249666842734-nhaobce9tet1k9uon0nbk7aj44ua45o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfZEOkE2UHFoANKC__i4fXwdIxDaR-6EQ',
    appId: '1:249666842734:ios:6196781f30f9ce7374b67f',
    messagingSenderId: '249666842734',
    projectId: 'basic-786d3',
    storageBucket: 'basic-786d3.appspot.com',
    iosClientId: '249666842734-nhaobce9tet1k9uon0nbk7aj44ua45o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
